# Generated by Django 5.2.5 on 2025-09-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together=set(),
        ),
    ]
