# Generated by Django 5.2.5 on 2025-09-26 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habitlog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
