# Generated by Django 5.2.5 on 2025-09-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_user_contact_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
