# Generated by Django 5.2.5 on 2025-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_unit_unittype_habit_time_of_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('achieved', 'Achieved'), ('failed', 'Failed'), ('progressing', 'Progressing')], default='progressing', max_length=20),
        ),
    ]
